language: php
php:
- 5.6
env:
  matrix:
  - WP_VERSION="~4.0.0"
  global:
    secure: h57AKa/r8gTanpVCRMh+pACDHskWcNsSGWiOAtYbgN1AkTnzx0N7Y31Umv6NNaqBdwF5wxFYY/LkuC5t6d/6UvGnYsDNul7u7NTVoQMcwgNhO7e/upUSuiTzE7R2vb2wsS+dzIhpiQyau73zjUQcf+68WoWJci6Xb+wGqmTlv0M=
services:
- mysql
install:
- npm install -g bower
- composer self-update
- sh -c "if $TRAVIS_SECURE_ENV_VARS; then composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
- wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
- java -jar selenium-server-standalone-2.44.0.jar > /dev/null 2>selenium-error.log
  &
before_script:
- cp .travis.composer.json composer.json
- composer install
- composer require --dev "johnpbloch/wordpress $WP_VERSION"
- mysql -e 'create database IF NOT EXISTS wordpress;'
- php -S localhost:8000 -t vendor/wordpress &> /dev/null &
- sleep 3
script:
- vendor/bin/behat
after_failure:
- cat selenium-error.log
